version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:8080"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=postgresql://crm_user:crm_password@db:5432/crm_db
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        flask db upgrade &&
        gunicorn --bind 0.0.0.0:8080 --workers 2 --reload run:app
      "

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=crm_password
      - POSTGRES_DB=crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
